# Site settings
title: ThoughtWorks China Pillar Three
email: china-p3@thoughtworks.com
description: At ThoughtWorks, we join the poor and oppressed in their demands for change. Why are there poor in this world where technology has helped create sufficient abundance to provide for basic needs including food, homes and care for all? We are determined to direct the power of technology for the benefit of those who need it most
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ThoughtWorks
github_username:  ThoughtWorks

# Build settings
markdown: kramdown
